# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Win32|x86|x64'
  buildConfiguration: 'Release'

pool:
  vmImage: windows-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      @echo off
      echo Hello World from %AGENT_NAME%.
      echo My ID is %AGENT_ID%.
      echo AGENT_WORKFOLDER contents:
      @dir %AGENT_WORKFOLDER%
      echo AGENT_BUILDDIRECTORY contents:
      @dir %AGENT_BUILDDIRECTORY%
      echo BUILD_SOURCESDIRECTORY contents:
      @dir %BUILD_SOURCESDIRECTORY%
      echo Over and out.

- task: BatchScript@1
  inputs:
    filename: '$(build.sourcesdirectory)/Builder/Build_HEVD_All.bat'
    workingFolder: '$(build.sourcesdirectory)/Builder'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build'
    Contents: '**'
    #contents: '**/$(BuildConfiguration)/**/?(*.sys|*.exe|*.dll|*.pdb)'
    targetFolder: '$(Build.BinariesDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_AntiRootkit'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'V3.$(Build.BuildId)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
