# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Win32|x86|x64'
  buildConfiguration: 'Release'

pool:
  vmImage: windows-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: BatchScript@1
  inputs:
    filename: '**/Builder/Build_HEVD_All.bat'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

