# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Win32|x86|x64'
  buildConfiguration: 'Release'

pool:
  vmImage: windows-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      @echo off
      echo Hello World from %AGENT_NAME%.
      echo My ID is %AGENT_ID%.
      echo AGENT_WORKFOLDER contents:
      @dir %AGENT_WORKFOLDER%
      echo AGENT_BUILDDIRECTORY contents:
      @dir %AGENT_BUILDDIRECTORY%
      echo BUILD_SOURCESDIRECTORY contents:
      @dir %BUILD_SOURCESDIRECTORY%
      echo Over and out.

- task: BatchScript@1
  inputs:
    filename: '//Builder/Build_HEVD_All.bat'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

